teleop_robot:
  ros__parameters:
    require_enable_button: true

    axis_linear:  
      x: 1                  # LS vertical
    scale_linear:
      x: 0.650
    scale_linear_turbo:
      x: 0.650

    axis_angular:  
      yaw: 0                # LS horizontal
    scale_angular:
      yaw: 9.6
    scale_angular_turbo:
      yaw: 9.6

    enable_turbo_button: 4  # LB
    enable_button: 5        # RB